version: '3'

services:
  wppconnect:
    image: wppconnect-team/wppconnect-server:latest
    container_name: wppconnect-server
    ports:
      - "21465:21465"
    environment:
      - PORT=21465
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - SECRET_KEY=THISISMYSECURETOKEN
    restart: always
    volumes:
      - ./tokens:/usr/src/app/tokens
