services:
  whatsapp:
    build: ./whatsapp-server
    container_name: whatsapp-server
    ports:
      - "4000:4000"
    volumes:
      - whatsapp_session:/data/session
    restart: always

volumes:
  whatsapp_session:
